### ISSUE TITLE
Reflect kyma evolution in the website 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/website#679]
**Description**

 - [ ] Reflect [new structure](https://github.com/kyma-project/kyma/issues/10857) in the documentation visible on website
 - [ ] Provide component describing the kyma ["in the nutshell"](https://github.com/kyma-project/website/issues/632)  
 - [ ] Put all the key website components together according to the [designs](https://github.com/kyma-project/website/issues/609)
     -  [manifesto](https://github.com/kyma-project/website/issues/624),
     -  [key features](https://github.com/kyma-project/website/issues/625),
     -  [used by](https://github.com/kyma-project/website/issues/630),
     -  [in the nutshell](https://github.com/kyma-project/website/issues/632) 
 - [ ] move the 'content-ui' out from kyma core chart
 
**Reasons**

Kyma evolved from an extensibility platform to an application runtime over the last few years. It should be reflected in the website.

**Attachments**
There are some additional components visible here ("Kyma convinced", "Check it out", "Meet kyma heroes") Lets keep them as stretch for now and add them gradually according to our development bandwidth.

![92358485-d3d1a700-f0e9-11ea-8dba-f80882155fbc](https://user-images.githubusercontent.com/6783567/110769704-c6dc6e80-8258-11eb-93c7-4c082f92dc23.jpg)

**Comment by kwiatekus** [comment]
Track progress via netlify preview here: https://github.com/kyma-project/website/pull/627/files
