### ISSUE TITLE
Adjust website to show kyma 2.0 content

### ISSUE THREAD

**Issue by dbadura** [kyma-project/website#728]
**Description**
Adjust kyma website to reflect the new strcutre of docs in kyma 2.0 https://github.com/kyma-project/kyma/issues/11029

**ToDo**
- [x] Links in Navigation has correct path: docs/{project}/{version}/topic
- [x] Highlight in navigation doesn't work for nesting deeper than 2 levels. Works, checked by
- [x] Assets are displayed in markdown view (links are correct)
- [x]  Logic which will add content to node (search for `index.md` in directory)
- [x] adapt content loader using bash
- [x] iItegrate kyma to work with docs_preview https://github.com/kyma-project/kyma/pull/11413
- [x] Integrate community to work with community_preview. https://github.com/kyma-project/community/pull/563 Ask @TW 
- [x] Enable Milv on kyma-2.0-docu test-infra: https://github.com/kyma-project/test-infra/pull/3776, kyma: https://github.com/kyma-project/kyma/pull/11484/files
- [x] Rename `index.md` to `README.md`
- [x] Contact TW about current integration
- [x] Sorting of nodes and leafs (dir and docs) 
- [x] Version picker shows last archived version and 2.0 and above 
- [x] Merge new landing page (https://github.com/kyma-project/website/pull/627)  to `new-navigation-tree`
- [x] Clean up code (remove unused code) @m00g3n 
- [x] Redirects to old documentation https://github.com/kyma-project/website/issues/700 @m00g3n 

**Improvements**:
- [x] Add logs which prints: `created page path`

**Current bugs**
- [x] Links between documentation don't work
- [x] Look at assets on this preview: https://app.netlify.com/sites/kyma-project-docs-preview/deploys/60be09217283dd00079df9b4
- [x] docs in root is not displayed: example `glossary` from this PR: https://github.com/kyma-project/kyma/pull/11397
- [x] Version picker doesn't work
- [x] Navigation bar doesn't work
- [x] Links in navigation doesn't work in docs:preview
- [x] Links with `latest` as version doesn't resolves correctly 
```
`/docs/latest/overview/first/second/01-trb-cannot-build-functions` -> page shows -> but in URL we have: `http://localhost:5000/docs/overview/first/second/01-trb-cannot-build-functions`
``` 
- [x] Fix 404 on docs-preview
- [x] when node doesn't have any markdown, the displayName is wrong and taken from one of it's child.
- [x] Investigate why `https://app.netlify.com/sites/kyma-project-community-preview/deploys/60b4d96069768d0007cec6ca` redirects to `https://02-diagrams/`
- [x] in community, such page is created `/community/README` which is `get-started/README.nd`
- [x] README.md is not treatet as root in community
- [x] Fix root docs page on docs-preview: `https://60afad1c59a4f70007f7b820--kyma-project-docs-preview.netlify.app/docs/kyma/2.0/` Returns 404, but locally works.
- [ ] Investigate possible performance impact when BUILD_FOR: website

**Release process**
- [x] create a temporary branch (on the website repo) which should contain all kyma 1x futures 
- [x] change the production branch (on the netlify for the `kyma-project.io` domain) from the main to temporary branch
- [x] provide all necessary changes to the main branch (support for the kyma 2x)
- [x] create a temporary site on the netlify to preview actual changes
- [x] switch again the production branch from the temporary to the main branch and cleanup temporary branch and site
By doing this, we can work on main branches without concern that we breaking production.

**Comment by kwiatekus** [comment]
New website is available at kyma-project.io
